# Generated by Django 3.0.9 on 2020-08-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.TextField(default='anonymous'),
            preserve_default=False,
        ),
    ]
